export const QUESTIONS = [
    {q:"Qual é o maior planeta do Sistema Solar?",a:["Terra","Marte","Júpiter","Vênus"],c:2},
    {q:"Qual animal é conhecido como o rei da selva?",a:["Leão","Elefante","Tigre","Urso"],c:0},
    {q:"Quantos dias tem uma semana?",a:["5","6","7","8"],c:2},
    {q:"Qual é a capital do Brasil?",a:["Rio de Janeiro","Brasília","São Paulo","Salvador"],c:1},
    {q:"Qual oceano banha a maior parte do litoral brasileiro?",a:["Pacífico","Índico","Atlântico","Ártico"],c:2},
    {q:"Quantos lados possui um triângulo?",a:["2","3","4","5"],c:1},
    {q:"Qual cor surge da mistura de azul e amarelo?",a:["Verde","Roxo","Laranja","Vermelho"],c:0},
    {q:"Em qual planeta vivemos?",a:["Marte","Saturno","Terra","Mercúrio"],c:2},
    {q:"Quantos meses existem em um ano?",a:["10","11","12","13"],c:2},
    {q:"Qual destes animais é um mamífero?",a:["Tubarão","Golfinho","Sardinha","Polvo"],c:1},
    {q:"Qual é o resultado de 8 x 7?",a:["54","56","58","64"],c:1},
    {q:"Qual é o maior oceano do planeta?",a:["Atlântico","Índico","Pacífico","Ártico"],c:2},
    {q:"Qual instrumento mede a temperatura?",a:["Barômetro","Termômetro","Velocímetro","Higrômetro"],c:1},
    {q:"Qual é a moeda oficial do Brasil?",a:["Peso","Real","Dólar","Euro"],c:1},
    {q:"Qual destes é um estado brasileiro?",a:["Lisboa","Paraná","Lima","Madri"],c:1},
    {q:"Quantas horas tem um dia?",a:["12","18","24","30"],c:2},
    {q:"Qual é o satélite natural da Terra?",a:["Sol","Lua","Marte","Vênus"],c:1},
    {q:"Qual destes é um metal?",a:["Ferro","Vidro","Madeira","Plástico"],c:0},
    {q:"Qual é o oposto de 'entrar'?",a:["Voltar","Sair","Subir","Abrir"],c:1},
    {q:"Qual destes animais pode voar?",a:["Pinguim","Galinha","Águia","Avestruz"],c:2},
    {q:"Quantos minutos tem uma hora?",a:["30","45","60","90"],c:2},
    {q:"Qual estação vem depois do inverno?",a:["Outono","Primavera","Verão","Inverno"],c:1},
    {q:"Qual destes é um continente?",a:["Amazonas","Europa","Sahara","Andes"],c:1},
    {q:"Qual é a soma de 25 + 17?",a:["40","41","42","43"],c:2},
    {q:"Qual órgão bombeia o sangue pelo corpo?",a:["Pulmão","Coração","Estômago","Rim"],c:1},
    {q:"Qual destas opções é uma fruta?",a:["Batata","Cenoura","Banana","Alface"],c:2},
    {q:"Qual gás respiramos em maior necessidade para viver?",a:["Oxigênio","Hélio","Hidrogênio","Neônio"],c:0},
    {q:"Qual destes números é par?",a:["7","9","12","15"],c:2},
    {q:"Quantos segundos tem um minuto?",a:["30","45","60","100"],c:2},
    {q:"Qual é a primeira letra do alfabeto?",a:["A","B","C","D"],c:0},
    {q:"Qual país é conhecido pelo formato de bota no mapa?",a:["Portugal","Itália","França","Grécia"],c:1},
    {q:"Qual destes é um planeta?",a:["Lua","Júpiter","Sol","Andrômeda"],c:1},
    {q:"Qual é o plural de 'cão'?",a:["Cãos","Cães","Cões","Cãoses"],c:1},
    {q:"Qual destes esportes usa uma bola laranja e cesta?",a:["Futebol","Vôlei","Basquete","Tênis"],c:2},
    {q:"Qual é a cor tradicional de uma esmeralda?",a:["Azul","Verde","Vermelha","Preta"],c:1},
    {q:"Quantos lados possui um quadrado?",a:["3","4","5","6"],c:1},
    {q:"Qual é o maior animal terrestre?",a:["Girafa","Elefante","Hipopótamo","Rinoceronte"],c:1},
    {q:"Qual destes é usado para escrever?",a:["Lápis","Prato","Copo","Sapato"],c:0},
    {q:"Qual é o resultado de 100 dividido por 4?",a:["20","25","30","40"],c:1},
    {q:"Qual destas cores faz parte da bandeira do Brasil?",a:["Roxo","Rosa","Verde","Cinza"],c:2},
    {"q":"Qual é a capital da Argentina?","a":["Buenos Aires","Córdoba","Rosário","Mendoza"],"c":0},
    {"q":"Qual é a capital do Chile?","a":["Santiago","Valparaíso","Concepción","Antofagasta"],"c":0},
    {"q":"Qual é a capital do Uruguai?","a":["Montevidéu","Salto","Punta del Este","Colônia"],"c":0},
    {"q":"Qual é a capital do Paraguai?","a":["Assunção","Ciudad del Este","Encarnación","San Lorenzo"],"c":0},
    {"q":"Qual é a capital do Peru?","a":["Lima","Cusco","Arequipa","Trujillo"],"c":0},
    {"q":"Qual é a capital da Colômbia?","a":["Bogotá","Medellín","Cali","Cartagena"],"c":0},
    {"q":"Qual é a capital do México?","a":["Cidade do México","Guadalajara","Monterrey","Cancún"],"c":0},
    {"q":"Qual é a capital de Portugal?","a":["Lisboa","Porto","Coimbra","Braga"],"c":0},
    {"q":"Qual é a capital da Espanha?","a":["Madri","Barcelona","Sevilha","Valência"],"c":0},
    {"q":"Qual é a capital da França?","a":["Paris","Lyon","Marselha","Nice"],"c":0},
    {"q":"Qual é a capital da Alemanha?","a":["Berlim","Munique","Hamburgo","Frankfurt"],"c":0},
    {"q":"Qual é a capital da Itália?","a":["Roma","Milão","Nápoles","Turim"],"c":0},
    {"q":"Qual é a capital da Inglaterra?","a":["Londres","Manchester","Liverpool","Birmingham"],"c":0},
    {"q":"Qual é a capital da Grécia?","a":["Atenas","Esparta","Tessalônica","Patras"],"c":0},
    {"q":"Qual é a capital do Japão?","a":["Tóquio","Osaka","Kyoto","Nagoya"],"c":0},
    {"q":"Qual é a capital da China?","a":["Pequim","Xangai","Guangzhou","Shenzhen"],"c":0},
    {"q":"Qual é a capital da Coreia do Sul?","a":["Seul","Busan","Incheon","Daegu"],"c":0},
    {"q":"Qual é a capital da Índia?","a":["Nova Délhi","Mumbai","Calcutá","Bangalore"],"c":0},
    {"q":"Qual é a capital do Canadá?","a":["Ottawa","Toronto","Vancouver","Montreal"],"c":0},
    {"q":"Qual é a capital dos Estados Unidos?","a":["Washington, D.C.","Nova York","Los Angeles","Chicago"],"c":0},
    {"q":"Qual é a capital da Austrália?","a":["Camberra","Sydney","Melbourne","Brisbane"],"c":0},
    {"q":"Qual é a capital do Egito?","a":["Cairo","Alexandria","Luxor","Gizé"],"c":0},
    {"q":"Qual é a capital da África do Sul legislativa?","a":["Cidade do Cabo","Joanesburgo","Durban","Pretória"],"c":0},
    {"q":"Em qual continente fica o Brasil?","a":["América do Sul","Europa","Ásia","África"],"c":0},
    {"q":"Em qual continente fica o Egito?","a":["África","Europa","Ásia","Oceania"],"c":0},
    {"q":"Em qual continente fica a Alemanha?","a":["Europa","Ásia","África","América"],"c":0},
    {"q":"Em qual continente fica o Japão?","a":["Ásia","Europa","África","Oceania"],"c":0},
    {"q":"Em qual continente fica a Austrália?","a":["Oceania","Ásia","Europa","África"],"c":0},
    {"q":"Qual linha imaginária divide a Terra em hemisfério norte e sul?","a":["Linha do Equador","Trópico de Câncer","Meridiano de Greenwich","Trópico de Capricórnio"],"c":0},
    {"q":"Qual é o maior país da América do Sul em área?","a":["Brasil","Argentina","Peru","Colômbia"],"c":0},
    {"q":"Qual é o maior país do mundo em área?","a":["Rússia","Canadá","China","Estados Unidos"],"c":0},
    {"q":"Qual é o deserto quente mais famoso do norte da África?","a":["Saara","Gobi","Atacama","Kalahari"],"c":0},
    {"q":"Qual cordilheira atravessa vários países da América do Sul?","a":["Andes","Alpes","Himalaia","Rochosas"],"c":0},
    {"q":"Qual rio passa pela cidade de Paris?","a":["Sena","Tâmisa","Danúbio","Reno"],"c":0},
    {"q":"Qual rio passa por Londres?","a":["Tâmisa","Sena","Nilo","Tejo"],"c":0},
    {"q":"Qual rio é associado ao Egito Antigo?","a":["Nilo","Amazonas","Danúbio","Mississippi"],"c":0},
    {"q":"Qual é o maior estado brasileiro em área?","a":["Amazonas","Pará","Mato Grosso","Bahia"],"c":0},
    {"q":"Qual é o menor estado brasileiro em área?","a":["Sergipe","Alagoas","Espírito Santo","Rio de Janeiro"],"c":0},
    {"q":"Qual estado brasileiro tem Salvador como capital?","a":["Bahia","Ceará","Pernambuco","Goiás"],"c":0},
    {"q":"Qual estado brasileiro tem Curitiba como capital?","a":["Paraná","Santa Catarina","Rio Grande do Sul","São Paulo"],"c":0},
    {"q":"Qual estado brasileiro tem Florianópolis como capital?","a":["Santa Catarina","Paraná","Rio Grande do Sul","Espírito Santo"],"c":0},
    {"q":"Qual estado brasileiro tem Porto Alegre como capital?","a":["Rio Grande do Sul","Santa Catarina","Paraná","São Paulo"],"c":0},
    {"q":"Qual estado brasileiro tem Recife como capital?","a":["Pernambuco","Paraíba","Alagoas","Ceará"],"c":0},
    {"q":"Qual estado brasileiro tem Fortaleza como capital?","a":["Ceará","Piauí","Maranhão","Rio Grande do Norte"],"c":0},
    {"q":"Qual estado brasileiro tem Goiânia como capital?","a":["Goiás","Tocantins","Mato Grosso","Minas Gerais"],"c":0},
    {"q":"Qual estado brasileiro tem Belo Horizonte como capital?","a":["Minas Gerais","Espírito Santo","Rio de Janeiro","São Paulo"],"c":0},
    {"q":"Qual estado brasileiro tem Vitória como capital?","a":["Espírito Santo","Rio de Janeiro","Bahia","Minas Gerais"],"c":0},
    {"q":"Qual estado brasileiro tem Manaus como capital?","a":["Amazonas","Acre","Roraima","Pará"],"c":0},
    {"q":"Qual estado brasileiro tem Belém como capital?","a":["Pará","Amapá","Amazonas","Maranhão"],"c":0},
    {"q":"Qual estado brasileiro tem Campo Grande como capital?","a":["Mato Grosso do Sul","Mato Grosso","Goiás","Paraná"],"c":0},
    {"q":"Qual estado brasileiro tem Cuiabá como capital?","a":["Mato Grosso","Mato Grosso do Sul","Goiás","Rondônia"],"c":0},
    {"q":"Quanto é 9 x 9?","a":["81","72","99","90"],"c":0},
    {"q":"Quanto é 12 x 12?","a":["144","124","132","154"],"c":0},
    {"q":"Quanto é 7 x 8?","a":["56","54","58","64"],"c":0},
    {"q":"Quanto é 15 + 27?","a":["42","41","43","44"],"c":0},
    {"q":"Quanto é 50 - 18?","a":["32","30","28","34"],"c":0},
    {"q":"Quanto é 72 dividido por 8?","a":["9","8","7","6"],"c":0},
    {"q":"Quanto é 81 dividido por 9?","a":["9","8","10","7"],"c":0},
    {"q":"Quanto é 11 x 6?","a":["66","60","72","64"],"c":0},
    {"q":"Quanto é 13 + 19?","a":["32","31","33","34"],"c":0},
    {"q":"Quanto é 100 - 37?","a":["63","67","73","57"],"c":0},
    {"q":"Quanto é 25 x 4?","a":["100","80","90","120"],"c":0},
    {"q":"Quanto é 3 ao quadrado?","a":["9","6","12","3"],"c":0},
    {"q":"Qual fração representa a metade?","a":["1/2","1/3","1/4","2/3"],"c":0},
    {"q":"Qual é a metade de 80?","a":["40","30","50","60"],"c":0},
    {"q":"Qual é o dobro de 45?","a":["90","80","100","85"],"c":0},
    {"q":"Qual é o triplo de 12?","a":["36","24","48","30"],"c":0},
    {"q":"Quantos centímetros tem um metro?","a":["100","10","1000","50"],"c":0},
    {"q":"Quantos metros tem um quilômetro?","a":["1000","100","10","10000"],"c":0},
    {"q":"Quantos gramas tem um quilograma?","a":["1000","100","500","10000"],"c":0},
    {"q":"Quantos mililitros tem um litro?","a":["1000","100","500","2000"],"c":0},
    {"q":"Quantos graus tem um ângulo reto?","a":["90","45","180","360"],"c":0},
    {"q":"Quantos graus tem uma volta completa?","a":["360","180","90","270"],"c":0},
    {"q":"Qual figura tem três lados?","a":["Triângulo","Quadrado","Pentágono","Hexágono"],"c":0},
    {"q":"Qual figura tem cinco lados?","a":["Pentágono","Quadrado","Hexágono","Triângulo"],"c":0},
    {"q":"Qual figura tem seis lados?","a":["Hexágono","Pentágono","Octógono","Triângulo"],"c":0},
    {"q":"Qual número romano representa 10?","a":["X","V","L","C"],"c":0},
    {"q":"Qual número romano representa 5?","a":["V","X","I","L"],"c":0},
    {"q":"Qual número romano representa 50?","a":["L","C","X","V"],"c":0},
    {"q":"Qual é o sucessor de 99?","a":["100","98","101","109"],"c":0},
    {"q":"Qual é o antecessor de 1000?","a":["999","998","1001","990"],"c":0},
    {"q":"Qual é a raiz quadrada de 64?","a":["8","6","7","9"],"c":0},
    {"q":"Qual é a raiz quadrada de 81?","a":["9","8","7","10"],"c":0},
    {"q":"Qual é a raiz quadrada de 100?","a":["10","20","5","50"],"c":0},
    {"q":"Qual planeta é conhecido como planeta vermelho?","a":["Marte","Vênus","Mercúrio","Saturno"],"c":0},
    {"q":"Qual planeta possui anéis muito visíveis?","a":["Saturno","Marte","Terra","Mercúrio"],"c":0},
    {"q":"Qual estrela fica no centro do Sistema Solar?","a":["Sol","Sirius","Lua","Vênus"],"c":0},
    {"q":"Qual é o nome da galáxia onde está o Sistema Solar?","a":["Via Láctea","Andrômeda","Sombrero","Triângulo"],"c":0},
    {"q":"Qual força nos mantém no chão?","a":["Gravidade","Magnetismo","Eletricidade","Pressão"],"c":0},
    {"q":"Qual estado da matéria tem forma e volume definidos?","a":["Sólido","Líquido","Gasoso","Plasma"],"c":0},
    {"q":"Qual estado da matéria assume a forma do recipiente mas mantém volume?","a":["Líquido","Sólido","Gasoso","Plasma"],"c":0},
    {"q":"Qual gás é mais abundante na atmosfera terrestre?","a":["Nitrogênio","Oxigênio","Gás carbônico","Hélio"],"c":0},
    {"q":"Qual órgão é responsável pela respiração?","a":["Pulmões","Rins","Fígado","Pâncreas"],"c":0},
    {"q":"Qual órgão filtra o sangue e produz urina?","a":["Rins","Pulmões","Coração","Estômago"],"c":0},
    {"q":"Qual órgão ajuda na digestão dos alimentos?","a":["Estômago","Pulmão","Cérebro","Coração"],"c":0},
    {"q":"Qual parte do corpo protege o cérebro?","a":["Crânio","Fêmur","Costela","Tíbia"],"c":0},
    {"q":"Qual é o maior órgão do corpo humano?","a":["Pele","Fígado","Pulmão","Coração"],"c":0},
    {"q":"Quantos dentes permanentes normalmente tem um adulto?","a":["32","28","30","36"],"c":0},
    {"q":"Quantos ossos aproximadamente tem o corpo humano adulto?","a":["206","180","250","300"],"c":0},
    {"q":"Qual vitamina é produzida na pele com ajuda da luz solar?","a":["Vitamina D","Vitamina C","Vitamina A","Vitamina K"],"c":0},
    {"q":"Qual mineral é importante para ossos e dentes?","a":["Cálcio","Sódio","Ferro","Iodo"],"c":0},
    {"q":"Qual substância compõe grande parte do corpo humano?","a":["Água","Ferro","Areia","Óleo"],"c":0},
    {"q":"Qual destes animais é réptil?","a":["Cobra","Golfinho","Sapo","Águia"],"c":0},
    {"q":"Qual destes animais é anfíbio?","a":["Sapo","Cachorro","Cobra","Tubarão"],"c":0},
    {"q":"Qual destes animais é ave?","a":["Papagaio","Morcego","Golfinho","Tartaruga"],"c":0},
    {"q":"Qual destes animais é inseto?","a":["Borboleta","Aranha","Escorpião","Minhoca"],"c":0},
    {"q":"Quantas patas tem uma aranha?","a":["8","6","10","4"],"c":0},
    {"q":"Quantas patas tem a maioria dos insetos?","a":["6","8","4","10"],"c":0},
    {"q":"Qual animal passa por metamorfose de lagarta para adulto?","a":["Borboleta","Formiga","Abelha","Besouro"],"c":0},
    {"q":"Qual animal produz mel?","a":["Abelha","Mosca","Vespa","Formiga"],"c":0},
    {"q":"Qual animal é conhecido por construir represas?","a":["Castor","Lontra","Coelho","Raposa"],"c":0},
    {"q":"Qual animal é famoso por sua tromba?","a":["Elefante","Girafa","Rinoceronte","Hipopótamo"],"c":0},
    {"q":"Qual animal tem pescoço muito longo?","a":["Girafa","Zebra","Leão","Búfalo"],"c":0},
    {"q":"Qual animal é conhecido por suas listras pretas e brancas?","a":["Zebra","Girafa","Leopardo","Panda"],"c":0},
    {"q":"Qual animal é símbolo da Austrália e se locomove saltando?","a":["Canguru","Coala","Dingo","Wombat"],"c":0},
    {"q":"Qual animal dorme pendurado de cabeça para baixo?","a":["Morcego","Pombo","Coelho","Raposa"],"c":0},
    {"q":"Qual animal marinho tem oito braços?","a":["Polvo","Lula","Caranguejo","Estrela-do-mar"],"c":0},
    {"q":"Qual mamífero marinho é conhecido por saltar e emitir sons?","a":["Golfinho","Tubarão","Atum","Arraia"],"c":0},
    {"q":"Qual é o maior mamífero do mundo?","a":["Baleia-azul","Elefante","Girafa","Hipopótamo"],"c":0},
    {"q":"Qual destes animais põe ovos?","a":["Galinha","Cachorro","Gato","Cavalo"],"c":0},
    {"q":"Qual destes animais é doméstico?","a":["Cachorro","Leão","Tigre","Lobo"],"c":0},
    {"q":"Qual destes alimentos é um cereal?","a":["Arroz","Tomate","Alface","Batata"],"c":0},
    {"q":"Qual destes alimentos é rico em vitamina C?","a":["Laranja","Arroz","Pão","Queijo"],"c":0},
    {"q":"Qual destes é um laticínio?","a":["Queijo","Arroz","Feijão","Maçã"],"c":0},
    {"q":"Qual alimento é feito principalmente com farinha e água?","a":["Pão","Arroz","Queijo","Carne"],"c":0},
    {"q":"Qual destes é uma leguminosa?","a":["Feijão","Batata","Cenoura","Alface"],"c":0},
    {"q":"Qual destes é uma fruta cítrica?","a":["Limão","Banana","Uva","Mamão"],"c":0},
    {"q":"Qual destes alimentos é produzido pelas abelhas?","a":["Mel","Leite","Farinha","Azeite"],"c":0},
    {"q":"Qual bebida é produzida a partir de folhas da planta Camellia sinensis?","a":["Chá","Café","Suco","Leite"],"c":0},
    {"q":"Qual grão é tradicionalmente usado para fazer pipoca?","a":["Milho","Arroz","Trigo","Aveia"],"c":0},
    {"q":"Qual destas bebidas é feita a partir de grãos torrados?","a":["Café","Suco de laranja","Água","Leite"],"c":0},
    {"q":"Qual destes alimentos é uma raiz?","a":["Cenoura","Alface","Tomate","Repolho"],"c":0},
    {"q":"Qual destes alimentos é um tubérculo?","a":["Batata","Alface","Laranja","Abacaxi"],"c":0},
    {"q":"Qual destas frutas tem sementes do lado de fora?","a":["Morango","Banana","Maçã","Pera"],"c":0},
    {"q":"Qual dessas frutas é amarela por fora quando madura?","a":["Banana","Uva roxa","Morango","Kiwi"],"c":0},
    {"q":"Qual é o ingrediente principal do guacamole?","a":["Abacate","Tomate","Batata","Manga"],"c":0},
    {"q":"Qual é a bebida feita ao espremer frutas?","a":["Suco","Café","Leite","Caldo"],"c":0},
    {"q":"Qual destes esportes é jogado com os pés?","a":["Futebol","Basquete","Tênis","Natação"],"c":0},
    {"q":"Quantos jogadores cada time de futebol normalmente tem em campo?","a":["11","10","9","12"],"c":0},
    {"q":"Qual esporte usa raquete e uma bola amarela?","a":["Tênis","Futebol","Basquete","Vôlei"],"c":0},
    {"q":"Qual esporte é praticado em uma piscina?","a":["Natação","Atletismo","Ciclismo","Judô"],"c":0},
    {"q":"Qual esporte usa uma cesta e bola laranja?","a":["Basquete","Vôlei","Handebol","Tênis"],"c":0},
    {"q":"Qual esporte usa uma rede e seis jogadores por lado em quadra?","a":["Vôlei","Futebol","Tênis","Rugby"],"c":0},
    {"q":"Qual esporte usa luvas e ringue?","a":["Boxe","Tênis","Golfe","Vôlei"],"c":0},
    {"q":"Qual esporte é disputado em pistas com carros?","a":["Automobilismo","Natação","Ginástica","Esgrima"],"c":0},
    {"q":"Qual esporte usa bicicleta?","a":["Ciclismo","Golfe","Judô","Tênis"],"c":0},
    {"q":"Qual esporte usa tacos e buracos em um campo?","a":["Golfe","Beisebol","Hóquei","Rugby"],"c":0},
    {"q":"Qual esporte usa espada, florete ou sabre?","a":["Esgrima","Boxe","Judô","Karate"],"c":0},
    {"q":"Qual luta japonesa é praticada sobre tatame?","a":["Judô","Boxe","Sumô aquático","Tênis"],"c":0},
    {"q":"Qual competição reúne modalidades como corrida, salto e arremesso?","a":["Atletismo","Natação","Basquete","Ciclismo"],"c":0},
    {"q":"Em qual esporte existe o termo 'gol'?","a":["Futebol","Tênis","Xadrez","Golfe"],"c":0},
    {"q":"Em qual esporte existe o termo 'ace' com frequência?","a":["Tênis","Futebol","Boxe","Natação"],"c":0},
    {"q":"Qual jogo de tabuleiro tem rei e rainha?","a":["Xadrez","Damas","Dominó","Ludo"],"c":0},
    {"q":"Qual jogo usa peças numeradas com pontos em duas metades?","a":["Dominó","Xadrez","Damas","Banco Imobiliário"],"c":0},
    {"q":"Qual jogo usa cartas com naipes como copas e espadas?","a":["Baralho","Dominó","Xadrez","Damas"],"c":0},
    {"q":"Qual personagem vive em uma casa de abacaxi no fundo do mar?","a":["Bob Esponja","Mickey Mouse","Pica-Pau","Scooby-Doo"],"c":0},
    {"q":"Qual personagem é um rato famoso da Disney?","a":["Mickey Mouse","Pato Donald","Pateta","Simba"],"c":0},
    {"q":"Qual personagem é um pato da Disney?","a":["Pato Donald","Mickey Mouse","Pateta","Pluto"],"c":0},
    {"q":"Qual personagem é conhecido como o ogro verde de um famoso filme de animação?","a":["Shrek","Simba","Buzz","Woody"],"c":0},
    {"q":"Qual personagem é um cowboy de Toy Story?","a":["Woody","Buzz","Shrek","Nemo"],"c":0},
    {"q":"Qual personagem de Toy Story é um patrulheiro espacial?","a":["Buzz Lightyear","Woody","Rex","Slinky"],"c":0},
    {"q":"Qual peixe é protagonista de Procurando Nemo?","a":["Nemo","Dory","Marlin","Bruce"],"c":0},
    {"q":"Qual personagem é um leão protagonista de O Rei Leão?","a":["Simba","Timão","Pumba","Scar"],"c":0},
    {"q":"Qual personagem é um cachorro medroso que resolve mistérios?","a":["Scooby-Doo","Pluto","Snoopy","Bolt"],"c":0},
    {"q":"Qual personagem costuma dizer 'que há, velhinho?'?","a":["Pernalonga","Patolino","Piu-Piu","Taz"],"c":0},
    {"q":"Qual super-herói é conhecido como Homem-Morcego?","a":["Batman","Superman","Aquaman","Flash"],"c":0},
    {"q":"Qual super-herói é conhecido por sua velocidade?","a":["Flash","Batman","Hulk","Thor"],"c":0},
    {"q":"Qual super-herói usa um escudo com estrela?","a":["Capitão América","Homem de Ferro","Thor","Hulk"],"c":0},
    {"q":"Qual herói é conhecido por usar um martelo chamado Mjolnir?","a":["Thor","Hulk","Batman","Flash"],"c":0},
    {"q":"Qual personagem verde fica muito forte quando se irrita?","a":["Hulk","Thor","Homem-Aranha","Superman"],"c":0},
    {"q":"Qual herói costuma lançar teias?","a":["Homem-Aranha","Batman","Thor","Aquaman"],"c":0},
    {"q":"Qual destes é um instrumento de cordas?","a":["Violão","Flauta","Trompete","Bateria"],"c":0},
    {"q":"Qual destes é um instrumento de sopro?","a":["Flauta","Violão","Piano","Bateria"],"c":0},
    {"q":"Qual destes é um instrumento de percussão?","a":["Bateria","Violino","Flauta","Saxofone"],"c":0},
    {"q":"Qual instrumento possui teclas pretas e brancas?","a":["Piano","Violão","Trompete","Tambor"],"c":0},
    {"q":"Qual instrumento geralmente tem seis cordas?","a":["Violão","Flauta","Trombone","Bateria"],"c":0},
    {"q":"Qual destes instrumentos é tocado com arco?","a":["Violino","Piano","Bateria","Flauta"],"c":0},
    {"q":"Qual nota vem depois de Dó na escala musical?","a":["Ré","Mi","Fá","Sol"],"c":0},
    {"q":"Qual nota vem depois de Sol?","a":["Lá","Fá","Mi","Dó"],"c":0},
    {"q":"Quantas notas principais há na escala musical tradicional?","a":["7","5","8","12"],"c":0},
    {"q":"Qual profissão trata dos dentes?","a":["Dentista","Engenheiro","Professor","Arquiteto"],"c":0},
    {"q":"Qual profissão costuma ensinar em escolas?","a":["Professor","Padeiro","Piloto","Mecânico"],"c":0},
    {"q":"Qual profissão trabalha com projetos de edifícios?","a":["Arquiteto","Dentista","Veterinário","Cozinheiro"],"c":0},
    {"q":"Qual profissão cuida da saúde de animais?","a":["Veterinário","Advogado","Professor","Motorista"],"c":0},
    {"q":"Qual profissão costuma pilotar aviões?","a":["Piloto","Médico","Padeiro","Carpinteiro"],"c":0},
    {"q":"Qual profissão prepara pães em uma padaria?","a":["Padeiro","Mecânico","Veterinário","Bombeiro"],"c":0},
    {"q":"Qual profissão combate incêndios?","a":["Bombeiro","Professor","Garçom","Pintor"],"c":0},
    {"q":"Qual profissão conserta carros?","a":["Mecânico","Dentista","Advogado","Professor"],"c":0},
    {"q":"Qual profissão geralmente prepara pratos em restaurantes?","a":["Cozinheiro","Piloto","Médico","Eletricista"],"c":0},
    {"q":"Qual profissão trabalha instalando e reparando fios elétricos?","a":["Eletricista","Padeiro","Dentista","Fotógrafo"],"c":0},
    {"q":"Qual objeto usamos para ver as horas?","a":["Relógio","Régua","Bússola","Termômetro"],"c":0},
    {"q":"Qual objeto usamos para medir comprimentos pequenos?","a":["Régua","Relógio","Balança","Bússola"],"c":0},
    {"q":"Qual objeto indica os pontos cardeais?","a":["Bússola","Régua","Termômetro","Calculadora"],"c":0},
    {"q":"Qual objeto usamos para medir massa?","a":["Balança","Régua","Relógio","Lupa"],"c":0},
    {"q":"Qual objeto amplia imagens pequenas?","a":["Lupa","Bússola","Tesoura","Régua"],"c":0},
    {"q":"Qual objeto usamos para cortar papel?","a":["Tesoura","Colher","Garfo","Prato"],"c":0},
    {"q":"Qual objeto usamos para apagar escrita a lápis?","a":["Borracha","Caneta","Régua","Tesoura"],"c":0},
    {"q":"Qual objeto usamos para proteger os olhos do sol?","a":["Óculos escuros","Chapéu de chuva","Relógio","Cinto"],"c":0},
    {"q":"Qual objeto protege a cabeça ao andar de bicicleta?","a":["Capacete","Luvas","Meias","Cinto"],"c":0},
    {"q":"Qual veículo anda sobre trilhos?","a":["Trem","Ônibus","Avião","Navio"],"c":0},
    {"q":"Qual veículo se desloca pelo ar?","a":["Avião","Trem","Navio","Ônibus"],"c":0},
    {"q":"Qual veículo se desloca principalmente pela água?","a":["Navio","Carro","Trem","Bicicleta"],"c":0},
    {"q":"Qual veículo normalmente tem duas rodas e pedais?","a":["Bicicleta","Ônibus","Avião","Navio"],"c":0},
    {"q":"Qual destes transportes costuma circular em cidades e levar muitos passageiros?","a":["Ônibus","Bicicleta","Patinete","Moto"],"c":0},
    {"q":"Qual cor é formada pela mistura de vermelho e azul?","a":["Roxo","Verde","Laranja","Amarelo"],"c":0},
    {"q":"Qual cor é formada pela mistura de vermelho e amarelo?","a":["Laranja","Roxo","Verde","Azul"],"c":0},
    {"q":"Qual dessas é uma cor primária tradicional?","a":["Azul","Verde","Roxo","Laranja"],"c":0},
    {"q":"Qual cor é geralmente associada ao céu em um dia claro?","a":["Azul","Verde","Vermelho","Roxo"],"c":0},
    {"q":"Qual cor é geralmente associada à grama?","a":["Verde","Azul","Roxo","Preto"],"c":0},
    {"q":"Qual cor resulta da mistura de branco e preto?","a":["Cinza","Rosa","Marrom","Verde"],"c":0},
    {"q":"Qual palavra é sinônimo de 'feliz'?","a":["Contente","Triste","Bravo","Cansado"],"c":0},
    {"q":"Qual palavra é antônimo de 'alto'?","a":["Baixo","Largo","Longo","Forte"],"c":0},
    {"q":"Qual palavra é antônimo de 'rápido'?","a":["Lento","Forte","Leve","Curto"],"c":0},
    {"q":"Qual palavra é sinônimo de 'bonito'?","a":["Belo","Feio","Velho","Fraco"],"c":0},
    {"q":"Qual palavra é antônimo de 'claro'?","a":["Escuro","Branco","Leve","Rápido"],"c":0},
    {"q":"Qual é o plural de 'papel'?","a":["Papéis","Papels","Papeis sem acento","Papelões"],"c":0},
    {"q":"Qual é o plural de 'animal'?","a":["Animais","Animals","Animales","Animal"],"c":0},
    {"q":"Qual é o plural de 'pão'?","a":["Pães","Pãos","Pões","Pãoses"],"c":0},
    {"q":"Qual dessas palavras é um verbo?","a":["Correr","Casa","Azul","Feliz"],"c":0},
    {"q":"Qual dessas palavras é um substantivo?","a":["Mesa","Correr","Bonito","Rapidamente"],"c":0},
    {"q":"Qual dessas palavras é um adjetivo?","a":["Bonito","Casa","Correr","Ontem"],"c":0},
    {"q":"Qual sinal termina uma pergunta?","a":["Ponto de interrogação","Ponto final","Vírgula","Dois-pontos"],"c":0},
    {"q":"Qual sinal costuma indicar uma pausa breve em uma frase?","a":["Vírgula","Ponto final","Interrogação","Parêntese"],"c":0},
    {"q":"Qual dia vem depois de segunda-feira?","a":["Terça-feira","Quarta-feira","Domingo","Sábado"],"c":0},
    {"q":"Qual dia vem antes de domingo?","a":["Sábado","Sexta-feira","Segunda-feira","Quinta-feira"],"c":0},
    {"q":"Qual mês vem depois de janeiro?","a":["Fevereiro","Março","Abril","Dezembro"],"c":0},
    {"q":"Qual mês vem antes de dezembro?","a":["Novembro","Outubro","Janeiro","Setembro"],"c":0},
    {"q":"Quantos dias normalmente tem fevereiro em um ano não bissexto?","a":["28","29","30","31"],"c":0},
    {"q":"Quantos dias tem abril?","a":["30","31","28","29"],"c":0},
    {"q":"Quantos dias tem julho?","a":["31","30","28","29"],"c":0},
    {"q":"Qual estação do ano é normalmente a mais quente?","a":["Verão","Inverno","Outono","Primavera"],"c":0},
    {"q":"Qual estação do ano é normalmente a mais fria?","a":["Inverno","Verão","Primavera","Outono"],"c":0},
    {"q":"Qual fenômeno acontece quando gotas de água caem das nuvens?","a":["Chuva","Vento","Neve","Orvalho"],"c":0},
    {"q":"Qual fenômeno é uma descarga elétrica atmosférica?","a":["Raio","Névoa","Orvalho","Arco-íris"],"c":0},
    {"q":"Qual fenômeno colorido pode aparecer no céu após chuva e sol?","a":["Arco-íris","Eclipse","Aurora","Tornado"],"c":0},
    {"q":"Qual instrumento é usado para observar objetos muito distantes no céu?","a":["Telescópio","Microscópio","Bússola","Régua"],"c":0},
    {"q":"Qual instrumento é usado para observar objetos muito pequenos?","a":["Microscópio","Telescópio","Binóculo","Bússola"],"c":0},
    {"q":"Qual destes materiais é transparente?","a":["Vidro limpo","Madeira","Pedra","Ferro"],"c":0},
    {"q":"Qual destes materiais é atraído por ímã com facilidade?","a":["Ferro","Vidro","Madeira","Plástico"],"c":0},
    {"q":"Qual destes materiais é feito de árvores?","a":["Papel","Vidro","Alumínio","Aço"],"c":0},
    {"q":"Qual destas fontes de energia é renovável?","a":["Solar","Carvão mineral","Petróleo","Gás natural"],"c":0},
    {"q":"Qual destas fontes de energia usa o vento?","a":["Eólica","Solar","Nuclear","Térmica"],"c":0},
    {"q":"Qual destas fontes de energia usa a luz do Sol?","a":["Solar","Eólica","Hidrelétrica","Geotérmica"],"c":0},
    {"q":"Qual destes resíduos é geralmente reciclável?","a":["Lata de alumínio","Restos de comida","Papel higiênico usado","Fralda descartável"],"c":0},
    {"q":"Qual atitude ajuda a economizar água?","a":["Fechar a torneira ao escovar os dentes","Deixar mangueira aberta","Tomar banhos muito longos","Lavar calçada todo dia"],"c":0},
    {"q":"Qual atitude ajuda a economizar energia?","a":["Apagar luzes desnecessárias","Deixar tudo ligado","Abrir geladeira sem necessidade","Usar lâmpadas acesas durante o dia"],"c":0},
    {"q":"Qual material costuma ir no coletor azul da reciclagem no Brasil?","a":["Papel","Vidro","Metal","Plástico"],"c":0},
    {"q":"Qual material costuma ir no coletor verde da reciclagem no Brasil?","a":["Vidro","Papel","Metal","Plástico"],"c":0},
    {"q":"Qual material costuma ir no coletor amarelo da reciclagem no Brasil?","a":["Metal","Papel","Vidro","Plástico"],"c":0},
    {"q":"Qual material costuma ir no coletor vermelho da reciclagem no Brasil?","a":["Plástico","Papel","Vidro","Metal"],"c":0}
  ];
